let HEIGHT = 1000;
let WIDTH = HEIGHT;

let PLAYER_SIZE = 50;
let PLAYER_X = WIDTH / 2 - PLAYER_SIZE / 2;
let PLAYER_Y = HEIGHT / 2 - PLAYER_SIZE / 2;

let NUM_SPIKES = 20;
let SPIKE_START_LENGTH = WIDTH / 4;
let SPIKE_WIDTH = HEIGHT / 20;
let SPIKE_X = 0;
let SPIKE_STEPS = 10;
let SPIKE_INCREMENT = (WIDTH / 2 - SPIKE_START_LENGTH) / SPIKE_STEPS;
