let HEIGHT = 800;
let WIDTH = HEIGHT;

let PLAYER_SIZE = 50;
let PLAYER_X = WIDTH / 2 - PLAYER_SIZE / 2;
let PLAYER_Y = HEIGHT / 2 - PLAYER_SIZE / 2;

let NUM_SNAKES_LEFT = 10;
let NUM_SNAKES_RIGHT = NUM_SNAKES_LEFT;
let SNAKE_START_LENGTH = WIDTH / 4;
let SNAKE_THICKNESS = HEIGHT / 20;
let SNAKE_START_X = 0;
let SNAKE_START_Y = 0.7 * HEIGHT;
let SNAKE_STEPS = 10;
let SNAKE_INCREMENT = (WIDTH / 2 - SNAKE_START_LENGTH) / SNAKE_STEPS;
