let HEIGHT = 1000;
let WIDTH = HEIGHT;

let NUM_SNAKES_LEFT = 10;
let NUM_SNAKES_RIGHT = NUM_SNAKES_LEFT;
let SNAKE_START_LENGTH = WIDTH / 4;
let SNAKE_THICKNESS = HEIGHT / 10;
let SNAKE_START_X = 0;
let SNAKE_START_Y = 0.65 * HEIGHT;
let SNAKE_STEPS = 5;
let SNAKE_INCREMENT = (WIDTH / 2 - SNAKE_START_LENGTH) / SNAKE_STEPS;

let PLAYER_SIZE = 50;
let PLAYER_X = WIDTH / 2 - PLAYER_SIZE / 2;
let PLAYER_Y = HEIGHT / 2 - PLAYER_SIZE / 2;
let PLAYER_WIDTH = WIDTH / 5;
let PLAYER_HEIGHT = HEIGHT / 5;
let PLAYER_HEALTH = 100;
let PLAYER_HEALTH_CHANGE = PLAYER_HEALTH / SNAKE_STEPS;
