let questions = [
  {
    question: "What output will `console.log(+true)` produce?",
    answers: ["0", "1", "Syntax error", "2"],
    correctAnswer: "1",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "What does `null == undefined` evaluate to?",
    answers: ["true", "false", "undefined", "null"],
    correctAnswer: "true",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following is not a literal?",
    answers: ["null", "true", "myVar", "-3.14"],
    correctAnswer: "myVar",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following is not a falsy value?",
    answers: ["' '", "null", "undefined", "[ ]"],
    correctAnswer: "[ ]",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following is not a primitive type?",
    answers: ["string", "object", "symbol", "undefined"],
    correctAnswer: "object",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following array methods doesn't create a new array?",
    answers: ["filter", "sort", "map", "reduce"],
    correctAnswer: "sort",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following statements is true for Javascript?",
    answers: ["Objects are immutable.", "Variables are untyped.", "Primitives are mutable.", "Constants are typed."],
    correctAnswer: "Variables are untyped.",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of these is not a global constant?",
    answers: ["-Infinity", "-0", "NaN", "-NaN"],
    correctAnswer: "-NaN",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which special value is returned if underflow occurs from a negative number?",
    answers: ["-Infinity", "-0", "0", "NaN"],
    correctAnswer: "-0",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "What will be the output of `console.log(0 === -0)`?",
    answers: ["null", "true", "false", "undefined"],
    correctAnswer: "true",
    language: "javascript",
    level: "beginner",
  },
];
