let questions = [
  // ---------------- beginner ----------------

  {
    question: "What will `+true` evaluate to?",
    answers: ["0", "1", "SyntaxError", "2"],
    correctAnswer: "1",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "What does `typeof NaN` evaluate to?",
    answers: ["number", "undefined", "null", "NaN"],
    correctAnswer: "number",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "What does `null == undefined` evaluate to?",
    answers: ["true", "false", "undefined", "null"],
    correctAnswer: "true",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following is not a literal?",
    answers: ["null", "true", "myVar", "-3.14"],
    correctAnswer: "myVar",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following is not a falsy value?",
    answers: ["' '", "null", "undefined", "[ ]"],
    correctAnswer: "[ ]",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following is not a truthy value?",
    answers: ["'false'", "'0'", "''", "[ ]"],
    correctAnswer: "''",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following is not a primitive type?",
    answers: ["string", "object", "symbol", "undefined"],
    correctAnswer: "object",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following array methods doesn't create a new array?",
    answers: ["filter", "sort", "map", "reduce"],
    correctAnswer: "sort",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following statements is true?",
    answers: ["Objects are immutable.", "Variables are untyped.", "Primitives are mutable.", "Constants are typed."],
    correctAnswer: "Variables are untyped.",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of these is not a global constant?",
    answers: ["-Infinity", "-0", "NaN", "-NaN"],
    correctAnswer: "-NaN",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which special value is returned if underflow occurs from a negative number?",
    answers: ["-Infinity", "-0", "0", "NaN"],
    correctAnswer: "-0",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "What will `0 === -0` evaluate to?",
    answers: ["null", "true", "false", "undefined"],
    correctAnswer: "true",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following is not a valid string delimiter?",
    answers: ["'", '"', "`", "{"],
    correctAnswer: "{",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Currently, which is not a meaningful escape sequence?",
    answers: ["\\b", "\\q", "\\n", "\\t"],
    correctAnswer: "\\q",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of these string methods doesn't return a Boolean?",
    answers: ["startsWith", "endsWith", "includes", "indexOf"],
    correctAnswer: "indexOf",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of this is a valid RegExp datatype?",
    answers: ["/^x/", "\\^x\\", "/^x\\", "\\^x/"],
    correctAnswer: "/^x/",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "If `x` is an array of length 2, what would `x[2]` return?",
    answers: ["null", "undefined", "Error object", "NaN"],
    correctAnswer: "undefined",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "What does `Number(undefined)` evaluate to?",
    answers: ["undefined", "1", "0", "NaN"],
    correctAnswer: "NaN",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "What does `Number(null)` evaluate to?",
    answers: ["undefined", "1", "0", "NaN"],
    correctAnswer: "0",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "If a variable is declared but not initialized, what's its value?",
    answers: ["undefined", "null", "0", "NaN"],
    correctAnswer: "undefined",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "If `let a = [], b = [];`, what would `a == b` evaluate to?",
    answers: ["undefined", "true", "false", "NaN"],
    correctAnswer: "false",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following will not return `NaN`?",
    answers: ["1 + 'x'", "1 * 'x'", "1 % 'x'", "1 - 'x'"],
    correctAnswer: "1 + 'x'",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "What would `Boolean(() =&gt; {})` evaluate to?",
    answers: ["undefined", "true", "false", "NaN"],
    correctAnswer: "true",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "What would `0 == '0' || 0 === '0'`, evaluate to?",
    answers: ["undefined", "true", "false", "null"],
    correctAnswer: "true",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which is not a valid syntax for a `for` loop?",
    answers: ["for(i; i &lt; x.length; i++)", "for(let i of x)", "for(const i of x)", "for(let i in x)"],
    correctAnswer: "for(i; i &lt; x.length; i++)",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following will not return `ll`?",
    answers: ["x.slice(2, 4);", "x.substring(2, 4);", "x[2] + x[3];", "x[2, 3];"],
    correctAnswer: "x[2, 3];",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "If `let x = [5, , 1];`, then what is `x[1]`?",
    answers: ["NaN", "null", "5", "undefined"],
    correctAnswer: "undefined",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "If `let x = [5, 1, ];`, then what is `x.length`?",
    answers: ["2", "3", "0", "undefined"],
    correctAnswer: "2",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following is not a valid identifier?",
    answers: ["a3", "_a3", "3a", "A3"],
    correctAnswer: "_a3",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "If `let x; y = 0;`, what would `x.[y++]` evaluate to?",
    answers: ["TypeError", "null", "undefined", "NaN"],
    correctAnswer: "TypeError",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following is not a valid operator?",
    answers: ["++", "delete", "??", "?!"],
    correctAnswer: "?!",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which keyword calls the parent constructor?",
    answers: ["new", "this", "super", "here"],
    correctAnswer: "super",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "If `let x = -2; ++x;`, what will `console.log(x--);` evaluate to?",
    answers: ["-2", "-1", "-3", "0"],
    correctAnswer: "-1",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "What will `3 &gt; 2 &gt; 1` evaluate to?",
    answers: ["true", "false", "SyntaxError", "TypeError"],
    correctAnswer: "false",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Do `1 + (2 + '3')` and `(1 + 2) + '3'` return same strings?",
    answers: ["true", "false", "SyntaxError", "TypeError"],
    correctAnswer: "false",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following operators is used for assignment?",
    answers: ["=", "==", "===", "===="],
    correctAnswer: "=",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which of the following is false?",
    answers: [
      "typeof null === 'null'",
      "typeof undefined === 'undefined'",
      "typeof Math.max === 'function'",
      "typeof [] === 'object'",
    ],
    correctAnswer: "typeof null === 'null'",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "After `let x = [1, 2]; delete x[0];`, what is `x.length`?",
    answers: ["0", "1", "2", "undefined"],
    correctAnswer: "2",
    language: "javascript",
    level: "beginner",
  },
  {
    question: "Which statement won't make interpreter jump to a different part of program?",
    answers: ["return;", "break;", "debugger;", "continue;"],
    correctAnswer: "debugger;",
    language: "javascript",
    level: "beginner",
  },

  // ---------------- intermediate ----------------

  {
    question: "Which primary expression is not a constant?",
    answers: ["true", "false", "null", "this"],
    correctAnswer: "this",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "Which of the following objects doesn't have a literal syntax?",
    answers: ["string", "symbol", "BigInt", "integer"],
    correctAnswer: "symbol",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "In `let [x, y, z] = [1, [2, 3]];`, what value is assigned to `z`?",
    answers: ["[2, 3]", "2", "3", "undefined"],
    correctAnswer: "undefined",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "Which option produces variable `x` without block scope?",
    answers: ["let x", "const x", "var x", "no way exists"],
    correctAnswer: "var x",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "What would [a, b, x] after `let x = 1; let [a, b] = [++x, x++];` is run?",
    answers: ["[2, 2, 3]", "[1, 2, 3]", "[2, 2, 2]", "[2, 3, 3]"],
    correctAnswer: "[2, 2, 3]",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "If `let x = { y: 1 };`, which is an invalid property access expression?",
    answers: ["x.y", "x['y']", "x?.y", "x?['y']"],
    correctAnswer: "x?['y']",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "If `let x; y = 0;`, what would `x?.[y++]` evaluate to?",
    answers: ["TypeError", "null", "undefined", "NaN"],
    correctAnswer: "undefined",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "Which of these will produce a TypeError?",
    answers: ["[...'hi'];", "[...new Set([1, 2])];", "[...[1, 2]];", "[...{ x: [1, 2] }];"],
    correctAnswer: "[...{ x: [1, 2] }];",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "None of the operators have the following arity:",
    answers: ["unary", "binary", "ternary", "quaternary"],
    correctAnswer: "quaternary",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "What does `'x' + + 'y'` evaluate to?",
    answers: ["xNaN", "x y", "TypeError", "xNaNy"],
    correctAnswer: "xNaN",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "What does `-3**2` evaluate to?",
    answers: ["-9", "9", "SyntaxError", "NaN"],
    correctAnswer: "SyntaxError",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "For which primitive type are `++x` and `x + 1` not equivalent?",
    answers: ["null", "boolean", "string", "number"],
    correctAnswer: "string",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "If `let p = { a: 'x', b: 'y' };`, which of the following is not true?",
    answers: ["'a' in p", "'b' in p", "'x' in p", "'constructor' in p"],
    correctAnswer: "'x' in p",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "After `let x = 5; var y = 6;` and `eval('let x = 1; var y = 2;')`, what will `x` and `y` be?",
    answers: ["5 and 2", "5 and 6", "1 and 6", "1 and 2"],
    correctAnswer: "5 and 2",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "If a `switch` in a function doesn't have a `default` case, what will it return for default case?",
    answers: ["undefined", "SyntaxError", "null", "last case value"],
    correctAnswer: "undefined",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "Which of the following is not an iterable object?",
    answers: ["string", "map", "generator", "set"],
    correctAnswer: "generator",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "Which of these is not a valid `for` loop?",
    answers: ["for(;;)", "for(i in x)", "for (let i = 0;;)", "all of them are valid"],
    correctAnswer: "all of them are valid",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "Which statement can be used with a statement label?",
    answers: ["break", "return", "throw", "with"],
    correctAnswer: "break",
    language: "javascript",
    level: "intermediate",
  },
  {
    question: "If `function f() { return this; }`, what will `typeof f()` be in strict mode?",
    answers: ["SyntaxError", "TypeError", "undefined", "object"],
    correctAnswer: "undefined",
    language: "javascript",
    level: "intermediate",
  },

  // ---------------- advanced ----------------

  {
    question: "Which is not a valid algorithm for object-to-primitive conversions?",
    answers: ["prefer-string", "prefer-number", "prefer-boolean", "no-preference"],
    correctAnswer: "prefer-boolean",
    language: "javascript",
    level: "advanced",
  },
  {
    question: "What's the standard way to refer to global object in any context?",
    answers: ["global", "globalThis", "window", "self"],
    correctAnswer: "globalThis",
    language: "javascript",
    level: "advanced",
  },
  {
    question: "In `let [x, y, ...z] = [1, [2, 3]];`, what value is assigned to `z`?",
    answers: ["[ ]", "null", "3", "undefined"],
    correctAnswer: "[ ]",
    language: "javascript",
    level: "advanced",
  },
  {
    question: "Which variable declaration method hoists it to the top of enclosing function?",
    answers: ["let x", "const x", "var x", "no method exists"],
    correctAnswer: "var x",
    language: "javascript",
    level: "advanced",
  },

  {
    question: "What would be the value of `tan` after `let {sin, cos, ...tan} = Math;`?",
    answers: ["function tan() { [native code] }", "{ }", "TypeError", "udefined"],
    correctAnswer: "{ }",
    language: "javascript",
    level: "advanced",
  },
  {
    question: "What is the length of string literal '😋'?",
    answers: ["1", "2", "0", "undefined"],
    correctAnswer: "2",
    language: "javascript",
    level: "advanced",
  },
  {
    question: "Which of the following is not an lvalue?",
    answers: ["variable", "literal", "object property", "array element"],
    correctAnswer: "literal",
    language: "javascript",
    level: "advanced",
  },
  {
    question: "Which is not a valid way to iterate over object (`o`) properties?",
    answers: [
      "for(let p in o)",
      "for(let p of o)",
      "for(let k of Object.keys(o))",
      "for(let [k, v] of Object.entries(o))",
    ],
    correctAnswer: "for(let p of o)",
    language: "javascript",
    level: "advanced",
  },
  {
    question: "How many times will `for/of` loop iterate over '❤️❌🤖' string?",
    answers: ["3", "5", "0", "2"],
    correctAnswer: "3",
    language: "javascript",
    level: "advanced",
  },
  {
    question: "Which of these is false for strict mode?",
    answers: [
      "Variable declaration isn't optional.",
      "Function parameters can't have duplicate names.",
      "The `with` statement isn't allowed.",
      "BigInt literals aren't allowed.",
    ],
    correctAnswer: "BigInt literals aren't allowed.",
    language: "javascript",
    level: "advanced",
  },
];
